host = 'mysql.sqlpub.com'  # 这里输入主机名称一般来说都是localhost
user = 'orangeisland66'  # 这里输入mysql用户名
password = 'HM1620kJfibETKIE'  # 这里输入密码
port = 3306  # 这里输入端口号
charset = 'utf8mb4'
database = 'orangeisland66'  # 这里选择数据库
rankedGradesTable = 'grades'
usersTable = 'usersInfo'
checkApplicationsTable = 'checkApplications'
