'''
2024/7/10
    Teacher_Window
by  沈智恺
'''
import tkinter as tk
#教师窗口设置
Teacher_window=tk.Tk()
Teacher_window.title("教师窗口")
Teacher_window.geometry("600x400")
l=tk.Label(Teacher_window,text='欢迎进入教师操作界面',font=("Arial",20))
l.grid(row=0,column=0)
l.pack()
var=tk.StringVar()
var.set(0)
#查询学生成绩窗口
def ConsultGrades():
    Teacher_window.destroy()
    page1 = tk.Tk()
    page1.title('学生成绩')
    page1.geometry("800x500")
    l1 = tk.Label(page1, text='学生成绩', font=("Arial", 20))
    l1.pack()
    page1.focus_force()
    page1.mainloop()
def ConsultAccountantInfo():
    Teacher_window.destroy()
    page3 = tk.Tk()
    page3.title('账号信息')
    page3.geometry("600x400")
    l3 = tk.Label(page3,text='账号信息', font=("Arial", 20))
    l3.pack()
    page3.focus_force()
    page3.mainloop()
def ChangePassword():
    Teacher_window.destroy()
    page4 = tk.Tk()
    page4.title('修改密码')
    page4.geometry("600x400")
    tk.Label(page4, text='修改密码', font=("Arial", 20)).pack()
    tk.Label(page4, text='原密码', font=("Arial",14)).place(x=100,y=75)
    tk.Label(page4, text='修改后密码', font=("Arial",14)).place(x=100,y=150)
    tk.Label(page4, text='确认密码', font=("Arial",14)).place(x=100,y=225)
    tk.Entry(page4, textvariable=var,show='*',width=50).place(x=180,y=80)
    tk.Entry(page4, textvariable=var,show='*',width=44).place(x=220, y=155)
    tk.Entry(page4, textvariable=var,show='*',width=47).place(x=200, y=230)
    page4.focus_force()
    page4.mainloop()
def ChangeUserName():
    Teacher_window.destroy()
    page5 = tk.Tk()
    page5.title('修改用户名')
    page5.geometry("600x200")
    page5.focus_force()
    tk.Label(page5, text='修改用户名', font=("Arial", 20)).pack()
    tk.Label(page5,text='修改后的用户名', font=("Arial",14)).place(x=50,y=90)
    tk.Entry(page5, textvariable=var,width=40).place(x=205,y=95)
    page5.mainloop()
Choice1=tk.Radiobutton(Teacher_window,text='查看学生成绩',anchor='center',font=("Arial",14),variable=var,value='查看学生成绩',command=ConsultGrades)
Choice1.pack(fill=tk.BOTH,expand=True)
Choice2=tk.Radiobutton(Teacher_window, text='成绩复核申请',anchor='center',font=("Arial",14),variable=var,value='成绩复核申请')
Choice2.pack(fill=tk.BOTH,expand=True)
Choice3=tk.Radiobutton(Teacher_window,text='查看当前账户信息',anchor='center',font=("Arial",14),variable=var,value='查看当前账户信息',command=ConsultAccountantInfo)
Choice3.pack(fill=tk.BOTH,expand=True)
Choice4=tk.Radiobutton(Teacher_window, text='修改密码',anchor='center',font=("Arial",14),variable=var,value='修改密码',command=ChangePassword)
Choice4.pack(fill=tk.BOTH,expand=True)
Choice5=tk.Radiobutton(Teacher_window,text='修改用户名',anchor='center',font=("Arial",14),variable=var,value='修改用户名',command=ChangeUserName)
Choice5.pack(fill=tk.BOTH,expand=True)
Choice6=tk.Radiobutton(Teacher_window, text='返回登录界面',anchor='center',font=("Arial",14), variable=var,value='返回登录界面')
Choice6.pack(fill=tk.BOTH,expand=True)
Teacher_window.mainloop()